### ISSUE TITLE
Wierd slow down on 3 identical objects

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/BambuStudio-SoftFever#332] opened 2023-02-20 07:37 UTC
[Latest 1.4.5 beta]
I noticed a weird slowdown on 3 identical objects where no slowdown would be required.
Sliced with normal perimeter generator so not Arachne.

Of course i can switch back to classical mode slowdown handling but it's wierd that this happens.
![image](https://user-images.githubusercontent.com/42968695/220041640-b59273fd-7e28-43d2-9e5c-2d8e88349ba0.png)

When sliced on classic mode slowdown all look good:
![image](https://user-images.githubusercontent.com/42968695/220041856-f06fbad0-383b-4f33-af49-e58820a92fdc.png)

3mf attached (zipped)
[slowdown.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10781377/slowdown.zip)

**Comment by zviratko** [comment] 2023-02-20 09:38
I was just about to file the same thing
I noticed slowdown where they were not before (and IMO not necessary but that comes up to the settings - assuming it's caused by the new "slow down for overhangs" implementation)
However doing it for only one of the objects is weird. In my case it looks like this:
<img width="1044" alt="Screenshot 2023-02-20 at 10 35 48" src="https://user-images.githubusercontent.com/3704384/220068506-cf3badc4-afb9-43ac-ad7f-b7ffdd61dc3f.png">

I think it
1) should be less aggressive out of the box if it's wanted behaviour
2) should be consistent :-)

**Comment by zviratko** [comment] 2023-02-20 09:42
Disabling Arachne but using the new slow down generation looks like this - looks more correct but still inconsistent with the same object:
<img width="1033" alt="Screenshot 2023-02-20 at 10 41 10" src="https://user-images.githubusercontent.com/3704384/220069441-a0283d51-f068-4d88-9fc5-6785d168888d.png">

**Comment by rovili** [comment] 2023-02-20 16:06
I have the exact same issue. Duplicated objects are slowed down to the minimal speed in the filament settings.

**Comment by SoftFever** [comment] 2023-02-20 17:35
Yeah, it's a bug that only happened on cloned objects.
I have just fixed it [c868798](https://github.com/SoftFever/BambuStudio-SoftFever/commit/c8687989e5eecab43fdfeee4a2b7cb52f87a31e7)

**Comment by SoftFever** [comment] 2023-02-20 17:37
This is the bug that delayed 1.4.5 release :(

**Comment by Prutsium** [comment] 2023-02-20 19:15
> This is the bug that delayed 1.4.5 release :(

This contains the fix? https://github.com/SoftFever/BambuStudio-SoftFever/actions/runs/4225839174

**Comment by Prutsium** [comment] 2023-02-20 19:17
Ah just noticed it contains [c868798](https://github.com/SoftFever/BambuStudio-SoftFever/commit/c8687989e5eecab43fdfeee4a2b7cb52f87a31e7)

**Comment by psiberfunk** [comment] 2023-02-21 02:35
Lol, also just noticed this.  Seems to only happen with classic slowdown algorithm  Here's 3 project files for replication, showing it happens with arachne or classic wall generator, but turns off when you turn off the new overhang speed algorithm:


[NewSlowDownCodeBug_ClassicWalls_ClassicOverhangSlowdownAlgorithm.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10789048/NewSlowDownCodeBug_ClassicWalls_ClassicOverhangSlowdownAlgorithm.zip)

**Comment by Prutsium** [comment] 2023-02-21 07:02
Looks good with the latest Nightly!
![image](https://user-images.githubusercontent.com/42968695/220271432-1377d31e-3b5c-4db4-9ab6-31be846f8798.png)

**Comment by SoftFever** [comment] 2023-02-22 14:49
Looks like we have sorted out the problem.
Closing it.

**Closed by SoftFever** 2023-02-22 14:49 UTC
Labels: bug
